version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6378:6379"
    networks:
      - net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - net

networks:
  net:
    driver: bridge